#!/usr/bin/env python3.8
import os
import sys

source, target = sys.argv[1], sys.argv[2]

directoy = os.path.dirname(source)
pfix = source.split('/')[-1].strip("*")


def popfirst(l, pfix):
    for f in l:
        file_path = "{}/{}".format(directoy, f)
        if f.endswith(pfix) and os.path.isfile(file_path):
            return file_path
    return ''


file_list = os.listdir(directoy)
file_list.sort()
source_file = popfirst(file_list, pfix)
if source_file:
    cmd = "cp '{}' '{}'".format(source_file, target)
    print(cmd)
    os.system(cmd)
